name: main
on:
  # run on push but only for the main branch
  push:
    branches:
      - main
  # run for every pull request
  pull_request: {}
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🤝 Set Node version from .nvmrc
        run: echo NVMRC=`cat .nvmrc` >> $GITHUB_ENV

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NVMRC }}

      - name: 📥 Download deps
        run: >
          find . -name package.json -maxdepth 4 -type f | while read -r file; do
            directory=$(dirname "$file")
            echo "\"package.json directory: $directory\""
            npm install
          done

      - name: 🧹 Check code formatting with Prettier
        run: >
          find . -name package.json -maxdepth 3 -type f | while read -r file; do
            directory=$(dirname "$file")
            echo "\"package.json directory: $directory\""
            cd "$directory" && npm run format:check && cd -
          done

      - name: 👕 Lint code with ESLint
        run: >
          find . -name package.json -maxdepth 3 -type f | while read -r file; do
            directory=$(dirname "$file")
            echo "\"package.json directory: $directory\""
            cd "$directory" && npm run lint && cd -
          done
