name: validate
on:
  # run on push but only for the main branch
  push:
    branches:
      - main
  # run for every pull request
  pull_request: {}
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 🧹 Check code formatting with Prettier
        run: >
          find . -name package.json -maxdepth 3 -type f | while read -r file; do
            directory=$(dirname "$file")
            cd "$directory" && npm run format:check && cd -
          done

      - name: 👕 Lint code with ESLint
        run: >
          find . -name package.json -maxdepth 3 -type f | while read -r file; do
            directory=$(dirname "$file")
            cd "$directory" && npm run lint && cd -
          done
